import type { CSSProperties } from "react";

export const baseFont =
  "var(--font-inter), -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const displayFont =
  "var(--font-syne), var(--font-inter), -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const editorTheme = {
  background: "#F7F6F9",
  surface: "#FFFFFF",
  surfaceSubtle: "#F9F9FA",
  surfaceRaised: "#FFFFFF",
  border: "#EDEEEF",
  borderStrong: "#E1E1E5",
  text: "#191919",
  textSoft: "#494A4D",
  muted: "#999999",
  mutedStrong: "#666666",
  primary: "#7C51F8",
  primaryHover: "#6D46E6",
  primarySoft: "#F4F3FF",
  focus: "rgba(124, 81, 248, 0.22)",
  danger: "#D83B3B",
  dangerSoft: "#FEF2F2",
} as const;

export const styles = {
  eyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 1.4,
    color: editorTheme.primary,
    fontFamily: displayFont,
    textTransform: "uppercase",
  },
  primaryButton: {
    height: 36,
    padding: "0 16px",
    borderRadius: 8,
    border: `1px solid ${editorTheme.primary}`,
    background: editorTheme.primary,
    color: "#FFFFFF",
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(124,81,248,0.18)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  inspector: {
    borderLeft: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    padding: 18,
    overflowY: "auto",
  },
  panelTitle: {
    color: editorTheme.text,
    fontSize: 13,
    fontWeight: 800,
    fontFamily: displayFont,
  },
  form: { display: "grid", gap: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  field: {
    display: "grid",
    gap: 7,
    fontSize: 12,
    fontWeight: 700,
    color: editorTheme.textSoft,
    fontFamily: baseFont,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    color: editorTheme.text,
    padding: "9px 10px",
    font: `13px ${baseFont}`,
    outline: "none",
    boxShadow: "0 1px 2px rgba(16,19,35,0.04)",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    color: editorTheme.text,
    padding: "9px 10px",
    font: `13px/1.4 ${baseFont}`,
    resize: "vertical",
    outline: "none",
    boxShadow: "0 1px 2px rgba(16,19,35,0.04)",
  },
  colorInput: {
    width: "100%",
    height: 38,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    padding: 4,
  },
  toggleRow: { display: "flex", gap: 14 },
  itemList: {
    display: "grid",
    gap: 8,
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "1fr 34px",
    gap: 8,
    alignItems: "center",
  },
  gridItemEditor: {
    display: "grid",
    gap: 8,
    padding: 8,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
  },
  checkLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: editorTheme.text,
    fontSize: 13,
    fontWeight: 700,
  },
  secondaryButton: {
    height: 34,
    padding: "0 14px",
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: "#EDEEEF",
    color: "#101323",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  smallButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    color: editorTheme.text,
    fontWeight: 800,
    cursor: "pointer",
  },
  segmented: {
    display: "inline-flex",
    padding: 3,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
  },
  segment: {
    height: 28,
    padding: "0 10px",
    borderRadius: 6,
    border: "none",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  ghostButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    color: "#101323",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
  },
  splitButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    height: 36,
    borderRadius: 8,
    overflow: "visible",
    boxShadow: "0 0 0 1px rgba(0,0,0,0.0)",
  },
  splitButtonMain: {
    height: 36,
    padding: "0 14px",
    borderRadius: "8px 0 0 8px",
    border: "none",
    background: editorTheme.primary,
    color: "#FFFFFF",
    fontWeight: 800,
    cursor: "pointer",
  },
  splitButtonCaret: {
    height: 36,
    width: 30,
    border: "none",
    borderLeft: "1px solid rgba(255,255,255,0.24)",
    borderRadius: "0 8px 8px 0",
    background: editorTheme.primary,
    color: "#FFFFFF",
    fontWeight: 800,
    cursor: "pointer",
    fontSize: 11,
  },
  exportMenu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    minWidth: 240,
    padding: 6,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    boxShadow: "0 18px 44px rgba(16,19,35,0.16)",
    display: "grid",
    gap: 2,
    zIndex: 40,
  },
  exportMenuItem: {
    display: "block",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: editorTheme.text,
    cursor: "pointer",
    width: "100%",
  },
  exportMenuItemActive: {
    background: editorTheme.primarySoft,
    borderColor: "#DCD6FF",
  },
  exportMenuItemHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exportMenuItemLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: editorTheme.text,
  },
  exportMenuItemCheck: {
    color: editorTheme.primary,
    fontWeight: 800,
  },
  exportMenuItemDesc: {
    marginTop: 3,
    fontSize: 11.5,
    color: editorTheme.mutedStrong,
    lineHeight: 1.35,
  },
} satisfies Record<string, CSSProperties>;
