import type { CSSProperties } from "react";

export const presentStyles = {
  root: {
    position: "fixed",
    inset: 0,
    zIndex: 60,
    background: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  stageWrap: {
    position: "relative",
    background: "#000",
  },
  controls: {
    position: "absolute",
    bottom: 22,
    left: "50%",
    transform: "translateX(-50%)",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 999,
    background: "rgba(16,20,30,0.78)",
    border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 18px 48px rgba(0,0,0,0.5)",
    color: "#f4f6fa",
    transition: "opacity 200ms ease",
  },
  controlButton: {
    minWidth: 36,
    height: 32,
    padding: "0 10px",
    borderRadius: 999,
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
  },
  exitButton: {
    fontSize: 11,
    letterSpacing: 1,
    background: "rgba(255,255,255,0.08)",
  },
  counter: {
    minWidth: 64,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
    fontSize: 12,
    fontWeight: 700,
    color: "#d8dfed",
  },
} satisfies Record<string, CSSProperties>;
