import type { CSSProperties } from "react";
import { displayFont, editorTheme } from "../editorStyles";

export const drawerStyles = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "flex-end",
    background: "rgba(16, 19, 35, 0.28)",
  },
  sidecarBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 32,
    background: "rgba(16, 19, 35, 0.12)",
  },
  drawer: {
    width: 360,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    boxShadow: "-24px 0 70px rgba(16,19,35,0.16)",
    padding: 18,
    overflowY: "auto",
  },
  themeDrawer: {
    width: 380,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    boxShadow: "-24px 0 70px rgba(16,19,35,0.16)",
    padding: 18,
    overflowY: "auto",
  },
  componentDrawer: {
    width: 340,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    boxShadow: "-16px 0 48px rgba(16,19,35,0.12)",
    padding: 18,
    overflowY: "auto",
  },
  slideLayoutDrawer: {
    position: "absolute",
    top: 0,
    width: 330,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: `1px solid ${editorTheme.border}`,
    borderRight: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    boxShadow: "-16px 0 48px rgba(16,19,35,0.12)",
    padding: 18,
    overflowY: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 18,
  },
  title: {
    margin: "6px 0 0",
    fontSize: 18,
    lineHeight: 1.2,
    color: editorTheme.text,
    fontFamily: displayFont,
  },
  iconRow: { display: "inline-flex", gap: 8 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    color: editorTheme.text,
    cursor: "pointer",
    fontSize: 16,
  },
  hint: {
    margin: "-6px 0 16px",
    color: editorTheme.mutedStrong,
    fontSize: 12,
    lineHeight: 1.45,
  },
  themePanel: {
    display: "grid",
    gap: 12,
    marginBottom: 16,
    padding: 12,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
  },
  themeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  addGrid: {
    marginTop: 20,
    paddingTop: 18,
    borderTop: `1px solid ${editorTheme.border}`,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  componentPanel: {
    marginTop: 14,
    padding: 12,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    display: "grid",
    gap: 10,
  },
  sectionTitle: {
    color: editorTheme.text,
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.4,
  },
  componentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 8,
  },
  componentButton: {
    minHeight: 44,
    border: `1px solid ${editorTheme.border}`,
    borderRadius: 8,
    background: editorTheme.surface,
    color: editorTheme.text,
    cursor: "pointer",
    display: "grid",
    gap: 3,
    justifyItems: "start",
    padding: "8px 10px",
    textAlign: "left",
  },
  componentName: {
    color: editorTheme.text,
    fontSize: 12,
    fontWeight: 800,
  },
  componentMeta: {
    color: editorTheme.mutedStrong,
    fontSize: 11,
  },
  componentHint: {
    marginTop: 10,
    color: editorTheme.mutedStrong,
    fontSize: 11,
    lineHeight: 1.4,
  },
  componentPreviewGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
  },
  componentPreviewCard: {
    border: `1px solid ${editorTheme.border}`,
    borderRadius: 8,
    background: editorTheme.surface,
    color: editorTheme.text,
    cursor: "pointer",
    display: "grid",
    gap: 7,
    padding: 10,
    textAlign: "left",
  },
  componentPreviewFrame: {
    width: "100%",
    aspectRatio: "16 / 9",
    borderRadius: 6,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    display: "block",
    overflow: "hidden",
    padding: 8,
    boxSizing: "border-box",
  },
  componentPreviewStage: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "block",
  },
  componentPreviewName: {
    color: editorTheme.text,
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1.25,
  },
  componentPreviewMeta: {
    color: editorTheme.mutedStrong,
    fontSize: 11,
  },
  slideLayoutGrid: {
    display: "grid",
    gap: 12,
  },
  slideLayoutCard: {
    border: `1px solid ${editorTheme.border}`,
    borderRadius: 8,
    background: editorTheme.surface,
    color: editorTheme.text,
    cursor: "pointer",
    display: "grid",
    gap: 8,
    padding: 10,
    textAlign: "left",
  },
  slideLayoutPreview: {
    display: "block",
    width: "100%",
    aspectRatio: "16 / 9",
    borderRadius: 6,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    overflow: "hidden",
  },
  slideLayoutName: {
    color: editorTheme.text,
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1.25,
  },
  slideLayoutMeta: {
    color: editorTheme.mutedStrong,
    fontSize: 11,
  },
  generatorPanel: {
    marginTop: 14,
    padding: 12,
    borderRadius: 8,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    display: "grid",
    gap: 10,
  },
} satisfies Record<string, CSSProperties>;
